//
//  TapStyle.swift
//  TapMonkeys
//
//  Created by Kevin Sullivan on 5/23/15.
//  Copyright (c) 2015 SideApps. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class TapStyle : NSObject {

    //// Cache

    private struct Cache {
        static var imageOfUnknownUnlock: UIImage?
        static var unknownUnlockTargets: [AnyObject]?
    }

    //// Drawing Methods

    public class func drawMainLetter(#letterColor: UIColor, character: String) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Letter Drawing
        let letterRect = CGRectMake(0, -0, 28, 28)
        let letterStyle = NSParagraphStyle.defaultParagraphStyle().mutableCopy() as! NSMutableParagraphStyle
        letterStyle.alignment = NSTextAlignment.Center

        let letterFontAttributes = [NSFontAttributeName: UIFont(name: "Noteworthy-Light", size: 27)!, NSForegroundColorAttributeName: letterColor, NSParagraphStyleAttributeName: letterStyle]

        let letterTextHeight: CGFloat = NSString(string: character).boundingRectWithSize(CGSizeMake(letterRect.width, CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: letterFontAttributes, context: nil).size.height
        CGContextSaveGState(context)
        CGContextClipToRect(context, letterRect);
        NSString(string: character).drawInRect(CGRectMake(letterRect.minX, letterRect.minY + (letterRect.height - letterTextHeight) / 2, letterRect.width, letterTextHeight), withAttributes: letterFontAttributes)
        CGContextRestoreGState(context)
    }

    public class func drawBuy(#frame: CGRect, buyText: String) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Rectangle Drawing
        let rectangleRect = CGRectMake(frame.minX + 5, frame.minY + 0.5, floor((frame.width - 5) * 0.97959 + 0.5), floor((frame.height - 0.5) * 0.98990 + 0.5))
        let rectanglePath = UIBezierPath(roundedRect: rectangleRect, cornerRadius: 10)
        UIColor.blackColor().setStroke()
        rectanglePath.lineWidth = 1
        rectanglePath.stroke()
        let rectangleStyle = NSParagraphStyle.defaultParagraphStyle().mutableCopy() as! NSMutableParagraphStyle
        rectangleStyle.alignment = NSTextAlignment.Center

        let rectangleFontAttributes = [NSFontAttributeName: UIFont(name: "AppleSDGothicNeo-SemiBold", size: 14)!, NSForegroundColorAttributeName: UIColor.blackColor(), NSParagraphStyleAttributeName: rectangleStyle]

        let rectangleTextHeight: CGFloat = NSString(string: buyText).boundingRectWithSize(CGSizeMake(rectangleRect.width, CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: rectangleFontAttributes, context: nil).size.height
        CGContextSaveGState(context)
        CGContextClipToRect(context, rectangleRect);
        NSString(string: buyText).drawInRect(CGRectMake(rectangleRect.minX, rectangleRect.minY + (rectangleRect.height - rectangleTextHeight) / 2, rectangleRect.width, rectangleTextHeight), withAttributes: rectangleFontAttributes)
        CGContextRestoreGState(context)
    }

    public class func drawUnknownUnlock() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Shadow Declarations
        let picShadow = NSShadow()
        picShadow.shadowColor = UIColor.blackColor().colorWithAlphaComponent(0.8)
        picShadow.shadowOffset = CGSizeMake(0.1, -0.1)
        picShadow.shadowBlurRadius = 3

        //// Oval Drawing
        let ovalRect = CGRectMake(5, 5, 90, 90)
        var ovalPath = UIBezierPath(ovalInRect: ovalRect)
        UIColor.whiteColor().setFill()
        ovalPath.fill()
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, picShadow.shadowOffset, picShadow.shadowBlurRadius, (picShadow.shadowColor as! UIColor).CGColor)
        UIColor.blackColor().setStroke()
        ovalPath.lineWidth = 0.5
        ovalPath.stroke()
        CGContextRestoreGState(context)
        var ovalTextContent = NSString(string: "???")
        let ovalStyle = NSParagraphStyle.defaultParagraphStyle().mutableCopy() as! NSMutableParagraphStyle
        ovalStyle.alignment = NSTextAlignment.Center

        let ovalFontAttributes = [NSFontAttributeName: UIFont(name: "Noteworthy-Light", size: 35)!, NSForegroundColorAttributeName: UIColor.blackColor(), NSParagraphStyleAttributeName: ovalStyle]

        let ovalTextHeight: CGFloat = ovalTextContent.boundingRectWithSize(CGSizeMake(ovalRect.width, CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: ovalFontAttributes, context: nil).size.height
        CGContextSaveGState(context)
        CGContextClipToRect(context, ovalRect);
        ovalTextContent.drawInRect(CGRectMake(ovalRect.minX, ovalRect.minY + (ovalRect.height - ovalTextHeight) / 2, ovalRect.width, ovalTextHeight), withAttributes: ovalFontAttributes)
        CGContextRestoreGState(context)
    }

    public class func drawBuyIncome(#frame: CGRect, buyText: String, buySubtext: String) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: CGRectMake(frame.minX + 5, frame.minY + 0.5, floor((frame.width - 5) * 0.97959 + 0.5), floor((frame.height - 0.5) * 0.98990 + 0.5)), cornerRadius: 10)
        UIColor.blackColor().setStroke()
        rectanglePath.lineWidth = 1
        rectanglePath.stroke()


        //// Text 2 Drawing
        let text2Rect = CGRectMake(frame.minX + 5, frame.minY + 7, frame.width - 10, floor((frame.height - 7) * 0.48837 + 0.5))
        let text2Style = NSParagraphStyle.defaultParagraphStyle().mutableCopy() as! NSMutableParagraphStyle
        text2Style.alignment = NSTextAlignment.Center

        let text2FontAttributes = [NSFontAttributeName: UIFont(name: "AppleSDGothicNeo-SemiBold", size: 14)!, NSForegroundColorAttributeName: UIColor.blackColor(), NSParagraphStyleAttributeName: text2Style]

        let text2TextHeight: CGFloat = NSString(string: buyText).boundingRectWithSize(CGSizeMake(text2Rect.width, CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: text2FontAttributes, context: nil).size.height
        CGContextSaveGState(context)
        CGContextClipToRect(context, text2Rect);
        NSString(string: buyText).drawInRect(CGRectMake(text2Rect.minX, text2Rect.minY + (text2Rect.height - text2TextHeight) / 2, text2Rect.width, text2TextHeight), withAttributes: text2FontAttributes)
        CGContextRestoreGState(context)


        //// Text 3 Drawing
        let text3Rect = CGRectMake(frame.minX + 5, frame.minY + 28, floor((frame.width - 5) * 0.97959 + 0.5), floor((frame.height - 28) * 0.95455 + 0.5))
        let text3Style = NSParagraphStyle.defaultParagraphStyle().mutableCopy() as! NSMutableParagraphStyle
        text3Style.alignment = NSTextAlignment.Center

        let text3FontAttributes = [NSFontAttributeName: UIFont(name: "AppleSDGothicNeo-Light", size: 13)!, NSForegroundColorAttributeName: UIColor.blackColor(), NSParagraphStyleAttributeName: text3Style]

        let text3TextHeight: CGFloat = NSString(string: buySubtext).boundingRectWithSize(CGSizeMake(text3Rect.width, CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: text3FontAttributes, context: nil).size.height
        CGContextSaveGState(context)
        CGContextClipToRect(context, text3Rect);
        NSString(string: buySubtext).drawInRect(CGRectMake(text3Rect.minX, text3Rect.minY + (text3Rect.height - text3TextHeight) / 2, text3Rect.width, text3TextHeight), withAttributes: text3FontAttributes)
        CGContextRestoreGState(context)
    }

    public class func drawLightbulb(#frame: CGRect, lightbulbColor: UIColor) {


        //// Subframes
        let group000000ff: CGRect = CGRectMake(frame.minX + floor(frame.width * 0.22000 + 0.5), frame.minY + floor(frame.height * 0.00000 - 0.45) + 0.95, floor(frame.width * 0.78731 - 0.23) - floor(frame.width * 0.22000 + 0.5) + 0.73, floor(frame.height * 0.99048 + 0.5) - floor(frame.height * 0.00000 - 0.45) - 0.95)


        //// Group #000000ff
        //// Bezier 3 Drawing
        var bezier3Path = UIBezierPath()
        bezier3Path.moveToPoint(CGPointMake(group000000ff.minX + 0.39922 * group000000ff.width, group000000ff.minY + 0.00487 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.56934 * group000000ff.width, group000000ff.minY + 0.00264 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.45527 * group000000ff.width, group000000ff.minY + -0.00129 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.51285 * group000000ff.width, group000000ff.minY + -0.00111 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.79933 * group000000ff.width, group000000ff.minY + 0.05151 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.65107 * group000000ff.width, group000000ff.minY + 0.00815 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.73153 * group000000ff.width, group000000ff.minY + 0.02396 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.99935 * group000000ff.width, group000000ff.minY + 0.25763 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.91474 * group000000ff.width, group000000ff.minY + 0.09793 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.98941 * group000000ff.width, group000000ff.minY + 0.17627 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.94301 * group000000ff.width, group000000ff.minY + 0.42452 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 1.00442 * group000000ff.width, group000000ff.minY + 0.31496 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.97928 * group000000ff.width, group000000ff.minY + 0.37167 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.85023 * group000000ff.width, group000000ff.minY + 0.54011 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.91626 * group000000ff.width, group000000ff.minY + 0.46415 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.88185 * group000000ff.width, group000000ff.minY + 0.50177 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.80906 * group000000ff.width, group000000ff.minY + 0.61793 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.82938 * group000000ff.width, group000000ff.minY + 0.56457 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.81942 * group000000ff.width, group000000ff.minY + 0.59148 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.76080 * group000000ff.width, group000000ff.minY + 0.78388 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.78894 * group000000ff.width, group000000ff.minY + 0.67281 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.77409 * group000000ff.width, group000000ff.minY + 0.72830 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.75195 * group000000ff.width, group000000ff.minY + 0.80017 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.75911 * group000000ff.width, group000000ff.minY + 0.78943 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.76003 * group000000ff.width, group000000ff.minY + 0.79612 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.72482 * group000000ff.width, group000000ff.minY + 0.80437 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.74472 * group000000ff.width, group000000ff.minY + 0.80421 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.73397 * group000000ff.width, group000000ff.minY + 0.80353 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.41473 * group000000ff.width, group000000ff.minY + 0.83067 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.62104 * group000000ff.width, group000000ff.minY + 0.81125 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.51735 * group000000ff.width, group000000ff.minY + 0.81919 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.34728 * group000000ff.width, group000000ff.minY + 0.83987 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.39209 * group000000ff.width, group000000ff.minY + 0.83334 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.36944 * group000000ff.width, group000000ff.minY + 0.83603 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.41584 * group000000ff.width, group000000ff.minY + 0.84409 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.36984 * group000000ff.width, group000000ff.minY + 0.84260 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.39294 * group000000ff.width, group000000ff.minY + 0.84318 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.44940 * group000000ff.width, group000000ff.minY + 0.84071 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.42739 * group000000ff.width, group000000ff.minY + 0.84486 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.43825 * group000000ff.width, group000000ff.minY + 0.84195 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.65075 * group000000ff.width, group000000ff.minY + 0.82200 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.51568 * group000000ff.width, group000000ff.minY + 0.83192 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.58295 * group000000ff.width, group000000ff.minY + 0.82528 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.72028 * group000000ff.width, group000000ff.minY + 0.82344 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.67382 * group000000ff.width, group000000ff.minY + 0.82124 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.69762 * group000000ff.width, group000000ff.minY + 0.81987 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.73667 * group000000ff.width, group000000ff.minY + 0.84489 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.73558 * group000000ff.width, group000000ff.minY + 0.82563 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.74390 * group000000ff.width, group000000ff.minY + 0.83677 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.70445 * group000000ff.width, group000000ff.minY + 0.85797 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.73071 * group000000ff.width, group000000ff.minY + 0.85223 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.71680 * group000000ff.width, group000000ff.minY + 0.85544 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.61222 * group000000ff.width, group000000ff.minY + 0.86760 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.67462 * group000000ff.width, group000000ff.minY + 0.86358 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.64329 * group000000ff.width, group000000ff.minY + 0.86574 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.43808 * group000000ff.width, group000000ff.minY + 0.86981 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.55436 * group000000ff.width, group000000ff.minY + 0.87063 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.49613 * group000000ff.width, group000000ff.minY + 0.87122 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.40963 * group000000ff.width, group000000ff.minY + 0.87305 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.42824 * group000000ff.width, group000000ff.minY + 0.86935 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.41900 * group000000ff.width, group000000ff.minY + 0.87173 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.34291 * group000000ff.width, group000000ff.minY + 0.88768 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.38688 * group000000ff.width, group000000ff.minY + 0.87697 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.36353 * group000000ff.width, group000000ff.minY + 0.88061 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.44324 * group000000ff.width, group000000ff.minY + 0.89394 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.37535 * group000000ff.width, group000000ff.minY + 0.89325 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.40968 * group000000ff.width, group000000ff.minY + 0.89370 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.65730 * group000000ff.width, group000000ff.minY + 0.87254 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.51370 * group000000ff.width, group000000ff.minY + 0.88423 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.58502 * group000000ff.width, group000000ff.minY + 0.87581 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.71439 * group000000ff.width, group000000ff.minY + 0.87629 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.67631 * group000000ff.width, group000000ff.minY + 0.87213 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.69710 * group000000ff.width, group000000ff.minY + 0.87060 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.71556 * group000000ff.width, group000000ff.minY + 0.90067 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.72940 * group000000ff.width, group000000ff.minY + 0.88116 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.72942 * group000000ff.width, group000000ff.minY + 0.89515 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.65912 * group000000ff.width, group000000ff.minY + 0.91126 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.69906 * group000000ff.width, group000000ff.minY + 0.90742 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.67842 * group000000ff.width, group000000ff.minY + 0.90906 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.45802 * group000000ff.width, group000000ff.minY + 0.91962 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.59267 * group000000ff.width, group000000ff.minY + 0.91748 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.52525 * group000000ff.width, group000000ff.minY + 0.91959 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.42208 * group000000ff.width, group000000ff.minY + 0.92355 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.44560 * group000000ff.width, group000000ff.minY + 0.91893 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.43388 * group000000ff.width, group000000ff.minY + 0.92178 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.35262 * group000000ff.width, group000000ff.minY + 0.93840 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.39845 * group000000ff.width, group000000ff.minY + 0.92765 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.37443 * group000000ff.width, group000000ff.minY + 0.93156 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.42213 * group000000ff.width, group000000ff.minY + 0.94500 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.37515 * group000000ff.width, group000000ff.minY + 0.94246 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.39875 * group000000ff.width, group000000ff.minY + 0.94377 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.57515 * group000000ff.width, group000000ff.minY + 0.94582 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.47303 * group000000ff.width, group000000ff.minY + 0.94732 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.52418 * group000000ff.width, group000000ff.minY + 0.94739 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.59764 * group000000ff.width, group000000ff.minY + 0.94051 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.58375 * group000000ff.width, group000000ff.minY + 0.94613 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.59046 * group000000ff.width, group000000ff.minY + 0.94266 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.66853 * group000000ff.width, group000000ff.minY + 0.92267 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.62022 * group000000ff.width, group000000ff.minY + 0.93329 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.64342 * group000000ff.width, group000000ff.minY + 0.92630 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.70570 * group000000ff.width, group000000ff.minY + 0.92480 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.68073 * group000000ff.width, group000000ff.minY + 0.92106 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.69511 * group000000ff.width, group000000ff.minY + 0.92001 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.70912 * group000000ff.width, group000000ff.minY + 0.95198 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.71976 * group000000ff.width, group000000ff.minY + 0.93097 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.72192 * group000000ff.width, group000000ff.minY + 0.94474 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.67117 * group000000ff.width, group000000ff.minY + 0.96329 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.69882 * group000000ff.width, group000000ff.minY + 0.95792 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.68476 * group000000ff.width, group000000ff.minY + 0.96087 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.59778 * group000000ff.width, group000000ff.minY + 0.97055 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.64727 * group000000ff.width, group000000ff.minY + 0.96740 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.62238 * group000000ff.width, group000000ff.minY + 0.96875 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.52291 * group000000ff.width, group000000ff.minY + 0.99840 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.57182 * group000000ff.width, group000000ff.minY + 0.97885 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.54768 * group000000ff.width, group000000ff.minY + 0.98898 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.49079 * group000000ff.width, group000000ff.minY + 0.98669 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.50900 * group000000ff.width, group000000ff.minY + 1.00334 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.48942 * group000000ff.width, group000000ff.minY + 0.99610 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.51091 * group000000ff.width, group000000ff.minY + 0.97223 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.49059 * group000000ff.width, group000000ff.minY + 0.97950 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.50217 * group000000ff.width, group000000ff.minY + 0.97579 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.36199 * group000000ff.width, group000000ff.minY + 0.96563 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.46113 * group000000ff.width, group000000ff.minY + 0.97213 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.41090 * group000000ff.width, group000000ff.minY + 0.97147 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.30974 * group000000ff.width, group000000ff.minY + 0.95301 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.34365 * group000000ff.width, group000000ff.minY + 0.96311 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.32438 * group000000ff.width, group000000ff.minY + 0.96030 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.30897 * group000000ff.width, group000000ff.minY + 0.92575 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.29601 * group000000ff.width, group000000ff.minY + 0.94640 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.29616 * group000000ff.width, group000000ff.minY + 0.93272 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.34077 * group000000ff.width, group000000ff.minY + 0.91361 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.31789 * group000000ff.width, group000000ff.minY + 0.92038 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.32952 * group000000ff.width, group000000ff.minY + 0.91700 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.30107 * group000000ff.width, group000000ff.minY + 0.90149 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.32646 * group000000ff.width, group000000ff.minY + 0.91107 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.31131 * group000000ff.width, group000000ff.minY + 0.90822 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.29921 * group000000ff.width, group000000ff.minY + 0.87661 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.29042 * group000000ff.width, group000000ff.minY + 0.89486 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.28987 * group000000ff.width, group000000ff.minY + 0.88380 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.32830 * group000000ff.width, group000000ff.minY + 0.86334 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.30661 * group000000ff.width, group000000ff.minY + 0.87070 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.31777 * group000000ff.width, group000000ff.minY + 0.86705 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.28756 * group000000ff.width, group000000ff.minY + 0.85287 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.31394 * group000000ff.width, group000000ff.minY + 0.86121 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.29839 * group000000ff.width, group000000ff.minY + 0.85922 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.28080 * group000000ff.width, group000000ff.minY + 0.83415 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.27902 * group000000ff.width, group000000ff.minY + 0.84822 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.27651 * group000000ff.width, group000000ff.minY + 0.84039 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.31258 * group000000ff.width, group000000ff.minY + 0.82067 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.28731 * group000000ff.width, group000000ff.minY + 0.82713 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.30070 * group000000ff.width, group000000ff.minY + 0.82380 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.42066 * group000000ff.width, group000000ff.minY + 0.80367 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.34728 * group000000ff.width, group000000ff.minY + 0.81248 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.38412 * group000000ff.width, group000000ff.minY + 0.80806 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.71774 * group000000ff.width, group000000ff.minY + 0.77909 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.51894 * group000000ff.width, group000000ff.minY + 0.79260 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.61838 * group000000ff.width, group000000ff.minY + 0.78575 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.77165 * group000000ff.width, group000000ff.minY + 0.59884 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.73225 * group000000ff.width, group000000ff.minY + 0.71869 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.74825 * group000000ff.width, group000000ff.minY + 0.65832 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.80313 * group000000ff.width, group000000ff.minY + 0.53870 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.78010 * group000000ff.width, group000000ff.minY + 0.57848 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.78864 * group000000ff.width, group000000ff.minY + 0.55796 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.86086 * group000000ff.width, group000000ff.minY + 0.46943 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.82121 * group000000ff.width, group000000ff.minY + 0.51528 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.84193 * group000000ff.width, group000000ff.minY + 0.49260 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.94733 * group000000ff.width, group000000ff.minY + 0.32712 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.89837 * group000000ff.width, group000000ff.minY + 0.42404 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.93158 * group000000ff.width, group000000ff.minY + 0.37688 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.95160 * group000000ff.width, group000000ff.minY + 0.23802 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.95635 * group000000ff.width, group000000ff.minY + 0.29780 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.96015 * group000000ff.width, group000000ff.minY + 0.26756 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.82143 * group000000ff.width, group000000ff.minY + 0.09507 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.93628 * group000000ff.width, group000000ff.minY + 0.18386 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.89020 * group000000ff.width, group000000ff.minY + 0.13265 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.60285 * group000000ff.width, group000000ff.minY + 0.03157 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.76134 * group000000ff.width, group000000ff.minY + 0.06193 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.68379 * group000000ff.width, group000000ff.minY + 0.04054 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.33481 * group000000ff.width, group000000ff.minY + 0.04241 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.51404 * group000000ff.width, group000000ff.minY + 0.02183 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.41962 * group000000ff.width, group000000ff.minY + 0.02268 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.07283 * group000000ff.width, group000000ff.minY + 0.19812 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.21482 * group000000ff.width, group000000ff.minY + 0.06970 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.12132 * group000000ff.width, group000000ff.minY + 0.12929 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.04389 * group000000ff.width, group000000ff.minY + 0.28373 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.05402 * group000000ff.width, group000000ff.minY + 0.22520 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.04138 * group000000ff.width, group000000ff.minY + 0.25432 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.11056 * group000000ff.width, group000000ff.minY + 0.43736 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.04588 * group000000ff.width, group000000ff.minY + 0.33709 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.07216 * group000000ff.width, group000000ff.minY + 0.38922 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.18650 * group000000ff.width, group000000ff.minY + 0.51906 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.13282 * group000000ff.width, group000000ff.minY + 0.46552 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.15893 * group000000ff.width, group000000ff.minY + 0.49257 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.27879 * group000000ff.width, group000000ff.minY + 0.65681 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.22918 * group000000ff.width, group000000ff.minY + 0.56187 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.25773 * group000000ff.width, group000000ff.minY + 0.60899 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.30729 * group000000ff.width, group000000ff.minY + 0.74123 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.29101 * group000000ff.width, group000000ff.minY + 0.68461 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.30040 * group000000ff.width, group000000ff.minY + 0.71281 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.49531 * group000000ff.width, group000000ff.minY + 0.74126 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.36996 * group000000ff.width, group000000ff.minY + 0.74127 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.43264 * group000000ff.width, group000000ff.minY + 0.74121 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.49531 * group000000ff.width, group000000ff.minY + 0.64459 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.49544 * group000000ff.width, group000000ff.minY + 0.70902 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.49544 * group000000ff.width, group000000ff.minY + 0.67681 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.46945 * group000000ff.width, group000000ff.minY + 0.52590 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.49298 * group000000ff.width, group000000ff.minY + 0.60465 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.48175 * group000000ff.width, group000000ff.minY + 0.56513 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.38367 * group000000ff.width, group000000ff.minY + 0.52140 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.44091 * group000000ff.width, group000000ff.minY + 0.52956 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.41058 * group000000ff.width, group000000ff.minY + 0.52805 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.28460 * group000000ff.width, group000000ff.minY + 0.46618 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.34057 * group000000ff.width, group000000ff.minY + 0.51085 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.30540 * group000000ff.width, group000000ff.minY + 0.49046 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.26876 * group000000ff.width, group000000ff.minY + 0.40649 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.26898 * group000000ff.width, group000000ff.minY + 0.44791 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.26153 * group000000ff.width, group000000ff.minY + 0.42669 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.31936 * group000000ff.width, group000000ff.minY + 0.35645 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.27531 * group000000ff.width, group000000ff.minY + 0.38720 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.29159 * group000000ff.width, group000000ff.minY + 0.36819 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.40047 * group000000ff.width, group000000ff.minY + 0.35081 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.34226 * group000000ff.width, group000000ff.minY + 0.34659 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.37433 * group000000ff.width, group000000ff.minY + 0.34362 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.45263 * group000000ff.width, group000000ff.minY + 0.38722 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.42610 * group000000ff.width, group000000ff.minY + 0.35772 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.44307 * group000000ff.width, group000000ff.minY + 0.37216 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.50055 * group000000ff.width, group000000ff.minY + 0.48753 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.47367 * group000000ff.width, group000000ff.minY + 0.41975 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.48709 * group000000ff.width, group000000ff.minY + 0.45372 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.56298 * group000000ff.width, group000000ff.minY + 0.43629 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.52681 * group000000ff.width, group000000ff.minY + 0.47299 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.54509 * group000000ff.width, group000000ff.minY + 0.45444 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.63925 * group000000ff.width, group000000ff.minY + 0.35757 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.58854 * group000000ff.width, group000000ff.minY + 0.41010 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.60981 * group000000ff.width, group000000ff.minY + 0.38242 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.69770 * group000000ff.width, group000000ff.minY + 0.33110 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.65368 * group000000ff.width, group000000ff.minY + 0.34584 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.67199 * group000000ff.width, group000000ff.minY + 0.33361 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.76480 * group000000ff.width, group000000ff.minY + 0.35845 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.72786 * group000000ff.width, group000000ff.minY + 0.32845 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.75585 * group000000ff.width, group000000ff.minY + 0.34238 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.75170 * group000000ff.width, group000000ff.minY + 0.41029 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.77446 * group000000ff.width, group000000ff.minY + 0.37585 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.76502 * group000000ff.width, group000000ff.minY + 0.39446 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.65738 * group000000ff.width, group000000ff.minY + 0.48123 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.72848 * group000000ff.width, group000000ff.minY + 0.43721 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.69400 * group000000ff.width, group000000ff.minY + 0.46021 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.53474 * group000000ff.width, group000000ff.minY + 0.53727 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.62002 * group000000ff.width, group000000ff.minY + 0.50234 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.57925 * group000000ff.width, group000000ff.minY + 0.52154 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.51819 * group000000ff.width, group000000ff.minY + 0.54014 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.52979 * group000000ff.width, group000000ff.minY + 0.53916 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.52393 * group000000ff.width, group000000ff.minY + 0.53979 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.53911 * group000000ff.width, group000000ff.minY + 0.64503 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.52823 * group000000ff.width, group000000ff.minY + 0.57484 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.53722 * group000000ff.width, group000000ff.minY + 0.60980 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.53916 * group000000ff.width, group000000ff.minY + 0.75340 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.53926 * group000000ff.width, group000000ff.minY + 0.68116 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.53913 * group000000ff.width, group000000ff.minY + 0.71729 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.52234 * group000000ff.width, group000000ff.minY + 0.76636 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.53990 * group000000ff.width, group000000ff.minY + 0.75936 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.53243 * group000000ff.width, group000000ff.minY + 0.76521 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.50033 * group000000ff.width, group000000ff.minY + 0.76679 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.51506 * group000000ff.width, group000000ff.minY + 0.76708 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.50766 * group000000ff.width, group000000ff.minY + 0.76670 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.29154 * group000000ff.width, group000000ff.minY + 0.76679 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.43075 * group000000ff.width, group000000ff.minY + 0.76678 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.36114 * group000000ff.width, group000000ff.minY + 0.76676 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.27253 * group000000ff.width, group000000ff.minY + 0.76311 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.28473 * group000000ff.width, group000000ff.minY + 0.76691 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.27740 * group000000ff.width, group000000ff.minY + 0.76609 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.26394 * group000000ff.width, group000000ff.minY + 0.74524 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.26426 * group000000ff.width, group000000ff.minY + 0.75850 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.26597 * group000000ff.width, group000000ff.minY + 0.75125 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.19709 * group000000ff.width, group000000ff.minY + 0.59126 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.25094 * group000000ff.width, group000000ff.minY + 0.69276 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.22973 * group000000ff.width, group000000ff.minY + 0.64081 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.13965 * group000000ff.width, group000000ff.minY + 0.52322 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.18136 * group000000ff.width, group000000ff.minY + 0.56768 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.16263 * group000000ff.width, group000000ff.minY + 0.54471 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.02488 * group000000ff.width, group000000ff.minY + 0.37701 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.09250 * group000000ff.width, group000000ff.minY + 0.47714 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.05027 * group000000ff.width, group000000ff.minY + 0.42879 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.00017 * group000000ff.width, group000000ff.minY + 0.26795 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.00750 * group000000ff.width, group000000ff.minY + 0.34164 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + -0.00135 * group000000ff.width, group000000ff.minY + 0.30476 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.03229 * group000000ff.width, group000000ff.minY + 0.18757 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.00228 * group000000ff.width, group000000ff.minY + 0.24028 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.01470 * group000000ff.width, group000000ff.minY + 0.21318 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.18551 * group000000ff.width, group000000ff.minY + 0.06391 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.06540 * group000000ff.width, group000000ff.minY + 0.14003 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.11792 * group000000ff.width, group000000ff.minY + 0.09688 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.39922 * group000000ff.width, group000000ff.minY + 0.00487 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.24657 * group000000ff.width, group000000ff.minY + 0.03403 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.32075 * group000000ff.width, group000000ff.minY + 0.01326 * group000000ff.height))
        bezier3Path.closePath()
        bezier3Path.moveToPoint(CGPointMake(group000000ff.minX + 0.68925 * group000000ff.width, group000000ff.minY + 0.36213 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.66026 * group000000ff.width, group000000ff.minY + 0.38578 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.67775 * group000000ff.width, group000000ff.minY + 0.36919 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.66898 * group000000ff.width, group000000ff.minY + 0.37754 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.57828 * group000000ff.width, group000000ff.minY + 0.47133 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.63167 * group000000ff.width, group000000ff.minY + 0.41388 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.60847 * group000000ff.width, group000000ff.minY + 0.44376 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.51039 * group000000ff.width, group000000ff.minY + 0.51588 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.55998 * group000000ff.width, group000000ff.minY + 0.48818 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.53846 * group000000ff.width, group000000ff.minY + 0.50421 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.60345 * group000000ff.width, group000000ff.minY + 0.47585 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.54370 * group000000ff.width, group000000ff.minY + 0.50448 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.57451 * group000000ff.width, group000000ff.minY + 0.49073 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.69929 * group000000ff.width, group000000ff.minY + 0.41287 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.63937 * group000000ff.width, group000000ff.minY + 0.45711 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.67300 * group000000ff.width, group000000ff.minY + 0.43653 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.72492 * group000000ff.width, group000000ff.minY + 0.37511 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.71144 * group000000ff.width, group000000ff.minY + 0.40135 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.72316 * group000000ff.width, group000000ff.minY + 0.38888 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.70632 * group000000ff.width, group000000ff.minY + 0.35628 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.72636 * group000000ff.width, group000000ff.minY + 0.36742 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.71936 * group000000ff.width, group000000ff.minY + 0.35883 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.68925 * group000000ff.width, group000000ff.minY + 0.36213 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.69936 * group000000ff.width, group000000ff.minY + 0.35641 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.69397 * group000000ff.width, group000000ff.minY + 0.35949 * group000000ff.height))
        bezier3Path.closePath()
        bezier3Path.moveToPoint(CGPointMake(group000000ff.minX + 0.35617 * group000000ff.width, group000000ff.minY + 0.37375 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.32077 * group000000ff.width, group000000ff.minY + 0.39503 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.33980 * group000000ff.width, group000000ff.minY + 0.37748 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.32815 * group000000ff.width, group000000ff.minY + 0.38600 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.31213 * group000000ff.width, group000000ff.minY + 0.43552 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.31091 * group000000ff.width, group000000ff.minY + 0.40756 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.30671 * group000000ff.width, group000000ff.minY + 0.42194 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.38169 * group000000ff.width, group000000ff.minY + 0.49214 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.32095 * group000000ff.width, group000000ff.minY + 0.45882 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.34726 * group000000ff.width, group000000ff.minY + 0.47944 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.46056 * group000000ff.width, group000000ff.minY + 0.50086 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.40479 * group000000ff.width, group000000ff.minY + 0.50073 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.43358 * group000000ff.width, group000000ff.minY + 0.50489 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.41639 * group000000ff.width, group000000ff.minY + 0.40361 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.44876 * group000000ff.width, group000000ff.minY + 0.46804 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.43524 * group000000ff.width, group000000ff.minY + 0.43531 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.38867 * group000000ff.width, group000000ff.minY + 0.37642 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.41028 * group000000ff.width, group000000ff.minY + 0.39368 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.40370 * group000000ff.width, group000000ff.minY + 0.38297 * group000000ff.height))
        bezier3Path.addCurveToPoint(CGPointMake(group000000ff.minX + 0.35617 * group000000ff.width, group000000ff.minY + 0.37375 * group000000ff.height), controlPoint1: CGPointMake(group000000ff.minX + 0.37957 * group000000ff.width, group000000ff.minY + 0.37227 * group000000ff.height), controlPoint2: CGPointMake(group000000ff.minX + 0.36686 * group000000ff.width, group000000ff.minY + 0.37120 * group000000ff.height))
        bezier3Path.closePath()
        bezier3Path.miterLimit = 4;

        lightbulbColor.setFill()
        bezier3Path.fill()
    }

    //// Generated Images

    public class var imageOfUnknownUnlock: UIImage {
        if Cache.imageOfUnknownUnlock != nil {
            return Cache.imageOfUnknownUnlock!
        }

        UIGraphicsBeginImageContextWithOptions(CGSizeMake(100, 100), false, 0)
            TapStyle.drawUnknownUnlock()

        Cache.imageOfUnknownUnlock = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return Cache.imageOfUnknownUnlock!
    }

    public class func imageOfLightbulb(#frame: CGRect, lightbulbColor: UIColor) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(frame.size, false, 0)
            TapStyle.drawLightbulb(frame: frame, lightbulbColor: lightbulbColor)

        let imageOfLightbulb = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfLightbulb
    }

    //// Customization Infrastructure

    @IBOutlet var unknownUnlockTargets: [AnyObject]! {
        get { return Cache.unknownUnlockTargets }
        set {
            Cache.unknownUnlockTargets = newValue
            for target: AnyObject in newValue {
                target.setImage(TapStyle.imageOfUnknownUnlock)
            }
        }
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
