//
//  TapStyle.swift
//  TapMonkeys
//
//  Created by Kevin Sullivan on 5/9/15.
//  Copyright (c) 2015 SideApps. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class TapStyle : NSObject {

    //// Drawing Methods

    public class func drawMainLetter(#character: String) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Letter Drawing
        let letterRect = CGRectMake(0, -0, 28, 28)
        let letterStyle = NSParagraphStyle.defaultParagraphStyle().mutableCopy() as! NSMutableParagraphStyle
        letterStyle.alignment = NSTextAlignment.Center

        let letterFontAttributes = [NSFontAttributeName: UIFont(name: "Noteworthy-Light", size: 27)!, NSForegroundColorAttributeName: UIColor.blackColor(), NSParagraphStyleAttributeName: letterStyle]

        let letterTextHeight: CGFloat = NSString(string: character).boundingRectWithSize(CGSizeMake(letterRect.width, CGFloat.infinity), options: NSStringDrawingOptions.UsesLineFragmentOrigin, attributes: letterFontAttributes, context: nil).size.height
        CGContextSaveGState(context)
        CGContextClipToRect(context, letterRect);
        NSString(string: character).drawInRect(CGRectMake(letterRect.minX, letterRect.minY + (letterRect.height - letterTextHeight) / 2, letterRect.width, letterTextHeight), withAttributes: letterFontAttributes)
        CGContextRestoreGState(context)
    }

    public class func drawFingerMonkey() {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()


        //// Shadow Declarations
        let shadow = NSShadow()
        shadow.shadowColor = UIColor.blackColor()
        shadow.shadowOffset = CGSizeMake(0.1, -0.1)
        shadow.shadowBlurRadius = 3

        //// Image Declarations
        let monkeyA = UIImage(named: "monkeyA.jpg")!

        //// Oval Drawing
        var ovalPath = UIBezierPath(ovalInRect: CGRectMake(5, 5, 90, 90))
        CGContextSaveGState(context)
        CGContextSetPatternPhase(context, CGSizeMake(0, 5))
        UIColor(patternImage: monkeyA).setFill()
        ovalPath.fill()
        CGContextRestoreGState(context)
        CGContextSaveGState(context)
        CGContextSetShadowWithColor(context, shadow.shadowOffset, shadow.shadowBlurRadius, (shadow.shadowColor as! UIColor).CGColor)
        UIColor.blackColor().setStroke()
        ovalPath.lineWidth = 0.5
        ovalPath.stroke()
        CGContextRestoreGState(context)
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
